FROM arm32v7/python:buster

MAINTAINER Walt Howd <walthowd@gmail.com>

WORKDIR /tmp/silabs

RUN apt-get update \
  && apt-get install -y git wget python3-pip unzip jq curl

#RUN wget https://bootstrap.pypa.io/2.7/get-pip.py --output-document=get-pip.py
#RUN python2 get-pip.py

#RUN pip install xmodem pyserial

RUN pip3 install xmodem pyserial

RUN mkdir -p /tmp/silabs

ADD update-firmware.sh /tmp/silabs
ADD ncp.py /tmp/silabs
ADD *.ebl /tmp/silabs/

CMD /tmp/silabs/update-firmware.sh
